-- MySQL Script generated by MySQL Workbench
-- Mon May  2 19:10:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Scada_Project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Scada_Project` ;

-- -----------------------------------------------------
-- Schema Scada_Project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Scada_Project` DEFAULT CHARACTER SET utf8 ;
USE `Scada_Project` ;

-- -----------------------------------------------------
-- Table `Scada_Project`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Scada_Project`.`person` (
  `CUI` BIGINT NOT NULL,
  `name_person` VARCHAR(100) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`CUI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Scada_Project`.`RFID_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Scada_Project`.`RFID_card` (
  `RFID_code` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`RFID_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Scada_Project`.`assign_RFID`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Scada_Project`.`assign_RFID` (
  `idassign_RFID` INT NOT NULL,
  `RFID_card_RFID_code` VARCHAR(100) NOT NULL,
  `person_CUI` BIGINT NOT NULL,
  `date` DATE NULL,
  `shift` INT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`idassign_RFID`),
  INDEX `fk_assign_RFID_RFID_card_idx` (`RFID_card_RFID_code` ASC),
  INDEX `fk_assign_RFID_person1_idx` (`person_CUI` ASC),
  CONSTRAINT `fk_assign_RFID_RFID_card`
    FOREIGN KEY (`RFID_card_RFID_code`)
    REFERENCES `Scada_Project`.`RFID_card` (`RFID_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assign_RFID_person1`
    FOREIGN KEY (`person_CUI`)
    REFERENCES `Scada_Project`.`person` (`CUI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Scada_Project`.`quantity_by_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Scada_Project`.`quantity_by_room` (
  `idquantity_by_room` INT NOT NULL,
  `quantity_by_reception` INT NULL,
  `general_room` INT NULL,
  `corridor` INT NULL,
  `clinic_room` INT NULL,
  `clinic` INT NULL,
  `exit` INT NULL,
  PRIMARY KEY (`idquantity_by_room`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
